# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180923_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='link',
            field=models.URLField(default='', verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nb_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of views'),
        ),
    ]
