# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180923_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(related_name='color_products', to='products.Color', verbose_name='Available colors'),
        ),
    ]
