# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180928_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card_image',
        ),
    ]
