# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 23:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181006_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='card_image',
        ),
        migrations.AddField(
            model_name='magazine',
            name='short_description',
            field=ckeditor.fields.RichTextField(default='lorem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magazine',
            name='nb_purchase',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of purchases'),
        ),
    ]
