# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181006_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='nb_purchase',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of views'),
        ),
    ]
