# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181008_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Is Published'),
        ),
    ]
