# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='File'),
        ),
    ]
