# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181009_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
