# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='square_item_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Square Item ID'),
        ),
    ]
