# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20181017_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='item',
            name='square_item_id',
        ),
        migrations.AddField(
            model_name='size',
            name='sku',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='size',
            name='square_item_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Square Item ID'),
        ),
    ]
