# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181021_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='item',
            name='available_sizes',
            field=models.ManyToManyField(related_name='size_products', to='products.Size', verbose_name='Available sizes'),
        ),
    ]
