# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20181021_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='size',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.FloatField(default=1.0, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
