# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 15:58
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20181021_1556'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='item',
            name='product_images',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='products.Image'),
        ),
    ]
