# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20181027_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='size_products', to='products.Size', verbose_name='Available sizes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.Tag', verbose_name='Tags'),
        ),
    ]
