# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 00:43
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.create(first_name='Dev', last_name='bienseance', username="dev@bienseance.ca",email="dev@bienseance.ca", password=make_password('a'), is_staff=True, is_superuser=True)


def delete_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email="dev@bienseance.com").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user, delete_user)
    ]
