# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 23:36
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSNamedMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('pages', jsonfield.fields.JSONField(blank=True, default=[], null=True)),
            ],
            options={
                'verbose_name': 'CMS Menu',
                'verbose_name_plural': 'CMS Menus',
            },
        ),
    ]
