# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0003_auto_20161019_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='Reciever',
        ),
    ]
