# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 03:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtranslation',
            name='short_description',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
