# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 23:35
from __future__ import unicode_literals

import apps.custom_plugins.validation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogtranslation_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtranslation',
            name='image',
            field=apps.custom_plugins.validation.ValidateImageFile(blank=True, upload_to=''),
        ),
    ]
