# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 23:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogtranslation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtranslation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
