# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 23:21
from __future__ import unicode_literals

import apps.custom_plugins.validation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180923_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtranslation',
            name='image',
            field=apps.custom_plugins.validation.ValidateImageFile(upload_to=''),
        ),
    ]
