# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_tag_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(to='blogs.BlogImage'),
        ),
    ]
