# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 23:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blog_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtranslation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Short Description'),
        ),
    ]
