# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 22:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('custom_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_plugins_textfield', serialize=False, to='cms.CMSPlugin')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
