# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 01:12
from __future__ import unicode_literals

import apps.custom_plugins.validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('custom_plugins', '0002_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackgroundImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_plugins_herobackgroundimage', serialize=False, to='cms.CMSPlugin')),
                ('photo', apps.custom_plugins.validation.ValidateImageFile(upload_to='cms', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
