# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('custom_plugins', '0003_herobackgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonField',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_plugins_buttonfield', serialize=False, to='cms.CMSPlugin')),
                ('link', models.URLField(verbose_name='Url')),
                ('text', models.CharField(max_length=30, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
