# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 23:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('custom_plugins', '0004_buttonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_plugins_eventcard', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('date_range', models.CharField(max_length=20, verbose_name='Dates')),
                ('location', ckeditor.fields.RichTextField()),
                ('time', models.CharField(max_length=100, verbose_name='Time')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
